apiVersion: v1
kind: Secret
metadata:
  name: kubecart-secret
  namespace: kubecart
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=