apiVersion: v1
kind: Service
metadata:
  name: kubecart-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP