apiVersion: v1
kind: Service

metadata:
  name: kubecart-nodeport
  namespace: kubecart

spec:
  type: NodePort
  selector:
    app: kubecart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080