apiVersion: v1
kind: Service
metadata:
  name: kubecart-service
  namespace: kubecart
spec:
  type: ClusterIP
  selector:
    app: kubecart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080