namespace: kubecart

replicaCount: 2

app:
  name: kubecart

deployment:
  name: kubecart-deployment

image:
  repository: kubecart-api
  tag: v1

serviceAccount:
  name: kubecart-sa

ingress:
  host: kubecart.local

resources:

  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi